<?php
session_start();
require_once __DIR__ . '/vendor/autoload.php'; // mPDF autoload
include('includes/scripts/connection.php');

if (!isset($_SESSION['pacpal_logedin_user_id'])) {
    die("Unauthorized access");
}

$user_id = $_SESSION['pacpal_logedin_user_id'];
$group_id = $_GET['group_id'] ?? 0;

// Fetch user & group details
$user_res = mysqli_query($conn, "SELECT user_name FROM user_master WHERE user_id = $user_id");
$user_name = mysqli_fetch_assoc($user_res)['user_name'] ?? 'Unknown';

$group_res = mysqli_query($conn, "SELECT group_name FROM group_master WHERE group_id = $group_id");
$group_name = mysqli_fetch_assoc($group_res)['group_name'] ?? 'Unknown Group';

// Fetch tasks with assigned user name
$sql = "
    SELECT 
        ci.item_name, 
        ci.status, 
        ci.note, 
        cc.category_name,
        um.user_name AS assigned_user
    FROM checklist_items ci
    JOIN checklist_categories cc ON ci.category_id = cc.cc_id
    JOIN user_master um ON ci.assigned_to = um.user_id
    WHERE cc.group_id = $group_id
";
$res = mysqli_query($conn, $sql);

// Count status
$total = $packed = $delivered = $not_started = 0;
$task_rows = '';
while ($task = mysqli_fetch_assoc($res)) {
    $total++;
    switch ($task['status']) {
        case 'Packed': $packed++; break;
        case 'Delivered': $delivered++; break;
        default: $not_started++;
    }

    $task_rows .= "
        <tr>
            <td>" . htmlspecialchars($task['item_name']) . "</td>
            <td>" . htmlspecialchars($task['category_name']) . "</td>
            <td>" . htmlspecialchars($task['assigned_user']) . "</td>
            <td>" . $task['status'] . "</td>
            <td>" . htmlspecialchars($task['note']) . "</td>
        </tr>
    ";
}

// HTML structure for PDF
$html = "
<style>
    body { font-family: sans-serif; }
    h2 { color: #0a657a; text-align: center; }
    .meta { margin-bottom: 20px; }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 15px;
    }
    table, th, td {
        border: 1px solid #aaa;
    }
    th {
        background-color: #0a657a;
        color: white;
        padding: 8px;
    }
    td {
        padding: 8px;
    }
    .summary {
        background-color: #f1f1f1;
        padding: 10px;
        font-weight: bold;
    }
</style>

<h2>PACPAL - Task Progress Report</h2>

<div class='meta'>
    <strong>Generated By:</strong> $user_name<br>
    <strong>Group:</strong> $group_name<br>
    <strong>Date:</strong> " . date("F j, Y") . "
</div>

<table>
    <thead>
        <tr>
            <th>Task Name</th>
            <th>Category</th>
            <th>Assigned To</th>
            <th>Status</th>
            <th>Note</th>
        </tr>
    </thead>
    <tbody>
        $task_rows
    </tbody>
</table>

<div class='summary'>
    Total Tasks: $total | Packed: $packed | Delivered: $delivered | Not Started: $not_started
</div>
";

// Generate PDF
$mpdf = new \Mpdf\Mpdf();
$mpdf->SetTitle("Task Report - $group_name");
$mpdf->WriteHTML($html);
$mpdf->Output(); // force download
// $mpdf->Output("Task_Report_$group_name.pdf", 'D'); // force download
?>
